### ISSUE TITLE
Data.Functor.Indexed should be Control.Functor.Indexed, because it contains only class

### ISSUE THREAD

**Issue by srghma** [garyb/purescript-indexed-monad#26]
https://github.com/garyb/purescript-indexed-monad/blob/master/src/Data/Functor/Indexed.purs

**Comment by garyb** [comment]
That's not what `Control` means, it's more to do with whether a class enables new control flow. Note that the non-indexed functor is `Data.Functor`, it's `Data.Functor` in Haskell, etc.
